### PR TITLE
Added tile randomization and rotation, as well as new game functionality

### PR DESCRIPTION
**Pull request by State307**

### CODE REVIEW

**Comment by MDFL64** [comment]
FYI this does not appear to reset the rotation. Judging by the amount of bold text in the assignment document we're probably going to lose points if it doesn't reset the rotation.

**Comment by MDFL64** [comment]
Also throws an exception if there's no tile to rotate, similar to the problem we were having earlier this afternoon. This doesn't seem to cause any real issues but it could upset Buckner.

**Comment by MDFL64** [comment]
I've contacted Auston about the problems, we're going to take a look at it in a little bit.

**Comment by MDFL64** [comment]
Still resolving some issues....

**Comment by alexgermann** [comment]
I'm not sure how to merge my pull request with this one so I'm gonna make a separate one. Resolved the issues with the resetGame. I'm not sure if you got my text or not, Adam, but we still need a "subtle notification" from the front end that a tile has been moved to an occupied space. Buckner suggested a screen flash or something similar, but whatever you want to do is fine.

**Comment by MDFL64** [comment]
Heads up, you can merge mine instead, it has these changes.

**Pull request merged**
